"""Minimal OpenAI-compatible LLM server used only by the E2E suite.

The real deployment talks to llama-server (see server/config.py). For the
browser automations we stand in a tiny HTTP server that answers exactly the
endpoints the chat engine probes:

  GET  /health                 -> 200            (is_llama_alive)
  POST /models/load            -> 200            (load_llama_model)
  POST /v1/chat/completions    -> SSE stream     (_llm_worker)

The completion is a fixed, deterministic reply so the tests are reproducible.
It is streamed in chunks with small delays so the browser's "working/thinking"
status is actually observable, exactly like a real llama-server stream.
"""

import json
import time

REPLY = (
    "I'm the E2E stub assistant. This reply was generated by the real chat "
    "engine against a real HTTP backend."
)

# A plain-text reply that stands in for a non-tool final answer after the
# engine has already dispatched a tool call and fed the result back to us.
TOOL_RESULT_REPLY = "Done. I created the task via the manage_tasks tool."

# When the user's message contains this marker, the stub emits a real OpenAI
# function call for "manage_tasks" instead of text, so the engine's genuine
# tool-dispatch pipeline (dispatch -> tasks DB -> follow-up LLM round) runs.
CREATE_TASK_MARKER = "E2E_CREATE_TASK"


def _extract_last_user_message(payload):
    try:
        for msg in reversed(payload.get("messages") or []):
            if isinstance(msg, dict) and msg.get("role") == "user":
                return msg
    except Exception:
        pass
    return None


def _extract_user_text(msg):
    if not msg:
        return ""
    raw = msg.get("content")
    if isinstance(raw, str):
        return raw
    if isinstance(raw, list):
        parts = [
            part.get("text", "")
            for part in raw
            if isinstance(part, dict) and part.get("type") == "text"
        ]
        return " ".join(parts).strip()
    return ""


def _task_title_from(message):
    if CREATE_TASK_MARKER in message:
        rest = message.split(CREATE_TASK_MARKER, 1)[1].strip()
        title = (rest.splitlines() or [rest])[0].strip()[:100]
        return title or "E2E Task"
    return None


def _make_reply(body):
    msg = _extract_last_user_message(json.loads(body)) if body else None
    echoed = _extract_user_text(msg)
    if echoed:
        return f'You said: "{echoed}". {REPLY}'
    return REPLY


def _sse_chunk(text):
    return (
        "data: "
        + json.dumps({"choices": [{"delta": {"content": text}, "index": 0}]})
        + "\n\n"
    ).encode()


class LlmStubServer:
    """A tiny threaded HTTP server with the llama-server surface."""

    def __init__(self, chunk_delay=0.25):
        self._chunk_delay = chunk_delay
        self._srv = None
        self.port = None
        self._thread = None

    def start(self, host="127.0.0.1", port=0):
        import http.server
        import socketserver

        chunk_delay = self._chunk_delay

        class Handler(http.server.BaseHTTPRequestHandler):
            def _json(self, status, data):
                payload = json.dumps(data).encode()
                self.send_response(status)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                self.wfile.write(payload)

            def do_GET(self):
                if self.path.rstrip("/") == "/health":
                    self._json(200, {"status": "ok"})
                else:
                    self.send_error(404)

            def do_POST(self):
                if self.path == "/models/load":
                    self._json(200, {"status": "ok", "result": True})
                    return
                if self.path != "/v1/chat/completions":
                    self.send_error(404)
                    return
                length = int(self.headers.get("Content-Length", 0) or 0)
                body = self.rfile.read(length) if length else b""
                payload = json.loads(body) if body else {}
                messages = payload.get("messages") or []

                # Round 2+ after a tool dispatch: the engine feeds the tool
                # result back, so answer with plain text now.
                has_tool_result = any(
                    isinstance(m, dict) and m.get("role") == "tool"
                    for m in messages
                )
                if has_tool_result:
                    reply = TOOL_RESULT_REPLY
                    self._stream_text(reply)
                    return

                title = _task_title_from(_extract_user_text(_extract_last_user_message(payload)))
                if title is not None:
                    self._stream_tool_call(title)
                    return

                reply = _make_reply(body)
                self._stream_text(reply)

            def _stream_text(self, reply):
                words = reply.split(" ")
                self.send_response(200)
                self.send_header("Content-Type", "text/event-stream")
                self.send_header("Cache-Control", "no-cache")
                self.send_header("Connection", "close")
                self.end_headers()
                self.close_connection = True
                for i in range(0, len(words), 6):
                    part = " ".join(words[i:i + 6]) + (" " if i + 6 < len(words) else "")
                    self.wfile.write(_sse_chunk(part))
                    self.wfile.flush()
                    time.sleep(chunk_delay)
                self.wfile.write(b"data: [DONE]\n\n")
                self.wfile.flush()

            def _stream_tool_call(self, title):
                args = json.dumps(
                    {"operation": "create", "title": title, "priority": "medium"},
                    ensure_ascii=False,
                )
                half = len(args) // 2
                calls = [
                    {
                        "index": 0,
                        "id": "call_e2e_manage_tasks",
                        "type": "function",
                        "function": {"name": "manage_tasks", "arguments": args[:half]},
                    },
                    {"index": 0, "function": {"arguments": args[half:]}},
                ]
                self.send_response(200)
                self.send_header("Content-Type", "text/event-stream")
                self.send_header("Cache-Control", "no-cache")
                self.send_header("Connection", "close")
                self.end_headers()
                self.close_connection = True
                for i, tc in enumerate(calls):
                    chunk = json.dumps(
                        {
                            "choices": [
                                {
                                    "delta": {
                                        "tool_calls": [tc],
                                        "content": None,
                                        "reasoning_content": None,
                                    },
                                    "index": 0,
                                }
                            ]
                        }
                    )
                    self.wfile.write(b"data: " + chunk.encode() + b"\n\n")
                    self.wfile.flush()
                    time.sleep(chunk_delay)
                self.wfile.write(b"data: [DONE]\n\n")
                self.wfile.flush()

            def log_message(self, *args):
                pass

        class Server(socketserver.ThreadingMixIn, http.server.HTTPServer):
            allow_reuse_address = True

        self._srv = Server((host, port), Handler)
        self.port = self._srv.server_address[1]
        self._thread = self._srv._thread = None
        import threading

        self._thread = threading.Thread(target=self._srv.serve_forever, daemon=True)
        self._thread.start()
        return self

    @property
    def base_url(self):
        return f"http://127.0.0.1:{self.port}"

    def stop(self):
        if self._srv:
            self._srv.shutdown()
            self._srv.server_close()


if __name__ == "__main__":
    stub = LlmStubServer().start(port=8099)
    print(f"LLM stub listening on {stub.base_url}", flush=True)
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        stub.stop()
