Status: active

To                         Action      From
--                         ------      ----
Anywhere on wlan0          ALLOW       Anywhere                  
3001/tcp                   ALLOW       Anywhere                  
5353/udp                   ALLOW       Anywhere                  
Anywhere on wlp2s0         ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
OpenSSH                    ALLOW       Anywhere                  
22/tcp on wg0              ALLOW       Anywhere                  
Anywhere (v6) on wlan0     ALLOW       Anywhere (v6)             
3001/tcp (v6)              ALLOW       Anywhere (v6)             
5353/udp (v6)              ALLOW       Anywhere (v6)             
Anywhere (v6) on wlp2s0    ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
OpenSSH (v6)               ALLOW       Anywhere (v6)             
22/tcp (v6) on wg0         ALLOW       Anywhere (v6)             

Anywhere                   ALLOW OUT   Anywhere on wlan0         
Anywhere                   ALLOW OUT   Anywhere on wlp2s0        
Anywhere                   ALLOW OUT   Anywhere on wg0           
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on wlan0    
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on wlp2s0   
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on wg0      

